<section class="container sell_on_ziwira_section">
 <form action="<?php echo Mage::getUrl('sellonziwira/index/save',array('_secure'=>true))?>" method="post" >
    <div class="left-checkout-section">
        <h2>Sell On Ziwira</h2>
        <div class="registration-section">
              <div class="sell-form-control">
                <label>Merchant Name <span>*</span></label>
                  <input type="text" name="merhcant-name"placeholder="" />
              </div>
              <div class="sell-form-control">
                <label>Owner/Representative Name <span>*</span></label>
                  <input type="text" name="owner-name" placeholder="" />
              </div>
              <div class="sell-form-control">
                <label>Company Name <span>*</span></label>
                  <input type="text" name="compnay-name" placeholder="" />
              </div>
              <div class="sell-form-control">
                <label>Website Url <span>*</span></label>
                  <input type="text" name="website-url" placeholder="" />
              </div>
              <div class="sell-form-control">
                <label>Email <span>*</span></label>
                  <input type="email" name="email"placeholder="" />
              </div>
          </div>
          <div class="login-section">
              <div class="sell-form-control">
                <label>Mobile <span>*</span></label>
                  <input type="text" name="mobile" placeholder="" />
              </div>
              <div class="sell-form-control">
                <label>Type of Product <span>*</span></label>
                  <input type="text" name="typeof-product" placeholder="" />
              </div>
              <div class="sell-form-control">
                <label>Type of Business <span>*</span></label>
                  <input type="text"name="typrof-business" placeholder="" />
              </div>
              <div class="sell-form-control">
                <label>Business Description <span>*</span></label>
                  <input type="text" name="business-desc" placeholder="" />
              </div>
              <input type="submit" class="sign-in-checkout-btn btn" value="SUBMIT"/>
          </div>
      </div>
    </form>
</section>
