<section id="mainContent" style="padding-bottom:0;">
	<div class="container">
		<div class="row">
			<div class="col-md-12">

                <div class="row">
                    <div class="col-md-9">
                        <div class="home-container-left ">
                            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_slider')->toHtml();?>
                            <div class="clearall hidden">
                              <div class="home-left-col pull-left">
                                <!-- <?php //echo $this->getLayout()->createBlock('cms/block')->setBlockId('head-cat')->toHtml(); ?> -->
                                <div class="recycle-block">
                                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('green-products')->toHtml(); ?>
                                </div>
                                <div class="recycle-block">
                                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('express-delivery')->toHtml(); ?>
                                </div>
                    
                              </div>
                              <div class="home-right-col pull-left">
                                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('home_slider')->toHtml();?>
                              </div>
                            </div>
                          </div>    	
                    </div>
                    
                    <div class="col-md-3">
                        <div class="home-container-right">
                                    
                          <div id='div-gpt-ad-1472827447864-0' class="googleAd" style="margin-bottom:15px;">
                              <script>
                              googletag.cmd.push(function() { googletag.display('div-gpt-ad-1472827447864-0'); });
                              </script>
                          </div>
                        
                        
                          <div id='div-gpt-ad-1472827447864-1' class="googleAd">
                              <script>
                              googletag.cmd.push(function() { googletag.display('div-gpt-ad-1472827447864-1'); });
                              </script>
                          </div>
                      </div>
                    </div>
                    
                </div>
                                  
                <div style="clear:both; margin-bottom:20px;"></div>                  
                                  
                <div class="row">
                    <div class="col-sm-4">
                        <div class="googleAd">
                            <div id='div-gpt-ad-1472827447864-2' >
                                  <script>
                                  googletag.cmd.push(function() { googletag.display('div-gpt-ad-1472827447864-2'); });
                                  </script>
                              </div>
                        </div>
                    </div>
                    
                    <div class="col-sm-4">
                        <div id='div-gpt-ad-1472827447864-3' class="googleAd" >
                              <script>
                              googletag.cmd.push(function() { googletag.display('div-gpt-ad-1472827447864-3'); });
                              </script>
                       </div>
                    </div>
                    
                    <div class="col-sm-4">
                        <div id='div-gpt-ad-1472827447864-4' class="googleAd">
                              <script>
                              googletag.cmd.push(function() { googletag.display('div-gpt-ad-1472827447864-4'); });
                              </script>
                        </div>
                    </div>
                    
                </div> 
                <div class="row">                 
                    <div class="featured-heading col-sm-12" style="padding-bottom:0;">
                        <div class="featured-title">
                          <h1><img src="<?php echo $this->getSkinUrl('images/featured-icon.png'); ?>" style="top:8px;" /> New Products</h1>
                        </div>
                    </div> 
               </div>  
			</div>
		</div>
	</div>
</section>                  
                  
                  
<section id="featured-item" class="carousal-container">
	<div class="container">
    	<div class="row">
        	<div class="col-sm-12">
            	<div class="featuredList owl-carousel">
                	<?php
                    	$category = Mage::getModel('catalog/category')->load(51);
$productCollection = Mage::getResourceModel('catalog/product_collection')
                                 ->addCategoryFilter($category)
                                 ->setPageSize(50);
						foreach($productCollection as $_product)
						{
							$product = Mage::getModel('catalog/product')->load($_product->getEntityId());
							$IsNew = $product->getIsNew();
							$IsSale = $product->getIsSale();
							$IsBestseller = $product->getIsBestseller();
					?>
                	<div class="item">
                    	<div class="product-box">
                    		<?php if($IsNew == 1):?>
                            <div class="flag-new-top flag-arrow-top"></div>
                            <div class="flag-text">new</div>
                            <?php endif;?>
                            <?php if($IsSale == 1):?>
                            <div class="flag-sale-top flag-arrow-top"></div>
                            <div class="flag-text">sale</div>
                            <?php endif;?>
                            <?php if($IsBestseller == 1):?>
                            <div class="flag-arrow-right"></div>
                            <div class="seller-arrow-text">best seller</div>
                            <?php endif;?>
                            <div class="recycle-flag"><img src="<?php echo $this->getSkinUrl('images/recycle-flag.png'); ?>"/></div>
                            <div class="productImage text-center">
                            	<a href="<?php echo $product->getProductUrl(); ?>"><img src="<?php echo Mage::helper('catalog/image')->init($product, 'small_image'); ?>" class="img-responsive"/></a>
                            </div>
                            <div class="prod-action text-center">
                                <a class="featured-add-to-cart" style="cursor:pointer" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getAddUrl($product); ?>')"><i class="icon-market" ></i><?php echo $this->__('Add to Cart') ?></a>
                                <a href="<?php echo $product->getProductUrl(); ?>" class="featured-quick-view"><i class="icon-search"></i>Quick View</a>
							</div>
                            
                            <div class="prod-info">
                            	<h2 class="prod-name"><?php echo $product->getName(); ?></h2>
                                <div class="price-box">
								<?php echo Mage::helper('core')->currency($product->getFinalPrice(),true,true); ?>
<?php if($product->getMsrp() !=''): ?>
  /<span class="old-price"><?php echo Mage::helper('core')->currency($product->getMsrp(),true,true); ?></span>
  <?php endif;?>



								</div>
                            </div>
                         </div>   
                    </div>
                    <?php
						}
					?>
                </div>
            </div>
        </div>
    </div>
</section>      


<section id="limited-offers" class="carousal-container">
	<div class="container">
    	<div class="row">
        	<div class="col-sm-12">
            	<div class="featured-heading" style="padding-top:0; margin-top:0px; margin-bottom:20px;">
                    <div class="featured-title">
                      <h1><img src="<?php echo $this->getSkinUrl('images/prod-icon.png'); ?>" style="top:8px;"> Limited Time Offers</h1>
                    </div>
                </div>
            	<div class="featuredList owl-carousel">
                	<?php
                    	$limitedTimeOfferCat = Mage::getModel('catalog/category')->load(50);
$ltoproductCollection = Mage::getResourceModel('catalog/product_collection')
                                 ->addCategoryFilter($limitedTimeOfferCat)
                                 ->setPageSize(50);
						foreach($ltoproductCollection  as $_product)
						{
							$product = Mage::getModel('catalog/product')->load($_product->getEntityId());
							$IsNew = $product->getIsNew();
							$IsSale = $product->getIsSale();
							$IsBestseller = $product->getIsBestseller();
					?>
                	<div class="item">
                    	<div class="product-box">
                    		<?php if($IsNew == 1):?>
                            <div class="flag-new-top flag-arrow-top"></div>
                            <div class="flag-text">new</div>
                            <?php endif;?>
                            <?php if($IsSale == 1):?>
                            <div class="flag-sale-top flag-arrow-top"></div>
                            <div class="flag-text">sale</div>
                            <?php endif;?>
                            <?php if($IsBestseller == 1):?>
                            <div class="flag-arrow-right"></div>
                            <div class="seller-arrow-text">best seller</div>
                            <?php endif;?>
                            <div class="recycle-flag"><img src="<?php echo $this->getSkinUrl('images/recycle-flag.png'); ?>"/></div>
                            <div class="productImage text-center">
                            	<a href="<?php echo $product->getProductUrl(); ?>"><img src="<?php echo Mage::helper('catalog/image')->init($product, 'small_image'); ?>" class="img-responsive"/></a>
                            </div>
                            <div class="prod-action text-center">
                                <a class="featured-add-to-cart" style="cursor:pointer" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getAddUrl($product); ?>')"><i class="icon-market" ></i><?php echo $this->__('Add to Cart') ?></a>
                                <a href="<?php echo $product->getProductUrl(); ?>" class="featured-quick-view"><i class="icon-search"></i>Quick View</a>
							</div>
                            
                            <div class="prod-info">
                            	<h2 class="prod-name"><?php echo $product->getName(); ?></h2>
                                <div class="price-box">
								<?php echo Mage::helper('core')->currency($product->getFinalPrice(),true,true); ?>
<?php if($product->getMsrp() !=''): ?>
  /<span class="old-price"><?php echo Mage::helper('core')->currency($product->getMsrp(),true,true); ?></span>
  <?php endif;?>



								</div>
                            </div>
                         </div>   
                    </div>
                    <?php
						}
					?>
                </div>
            </div>
        </div>
        
        <div class="row">                 
            <div class="featured-heading col-sm-12" style="padding-bottom:0;">
                <div class="featured-title">
                  <h1><img src="<?php echo $this->getSkinUrl('images/hot-icon.png'); ?>" style="top:8px;" /> Best Seller</h1>
                </div>
            </div> 
       </div>  
        
    </div>	
</section>   

<section id="best-item" class="carousal-container">
	<div class="container">
    	<div class="row">
        	<div class="col-sm-12">
            	<div class="featuredList owl-carousel">
                	<?php
                    	$bestSellersCat = Mage::getModel('catalog/category')->load(52);
$BsproductCollection = Mage::getResourceModel('catalog/product_collection')
                                 ->addCategoryFilter($bestSellersCat)
                                 ->setPageSize(50);
						foreach($BsproductCollection as $_product)
						{
							$product = Mage::getModel('catalog/product')->load($_product->getEntityId());
							$IsNew = $product->getIsNew();
							$IsSale = $product->getIsSale();
							$IsBestseller = $product->getIsBestseller();
					?>
                	<div class="item">
                    	<div class="product-box">
                    		<?php if($IsNew == 1):?>
                            <div class="flag-new-top flag-arrow-top"></div>
                            <div class="flag-text">new</div>
                            <?php endif;?>
                            <?php if($IsSale == 1):?>
                            <div class="flag-sale-top flag-arrow-top"></div>
                            <div class="flag-text">sale</div>
                            <?php endif;?>
                            <?php if($IsBestseller == 1):?>
                            <div class="flag-arrow-right"></div>
                            <div class="seller-arrow-text">best seller</div>
                            <?php endif;?>
                            <div class="recycle-flag"><img src="<?php echo $this->getSkinUrl('images/recycle-flag.png'); ?>"/></div>
                            <div class="productImage text-center">
                            	<a href="<?php echo $product->getProductUrl(); ?>"><img src="<?php echo Mage::helper('catalog/image')->init($product, 'small_image'); ?>" class="img-responsive"/></a>
                            </div>
                            <div class="prod-action text-center">
                                <a class="featured-add-to-cart" style="cursor:pointer" title="<?php echo $this->quoteEscape($this->__('Add to Cart')) ?>" onclick="setLocation('<?php echo Mage::helper('checkout/cart')->getAddUrl($product); ?>')"><i class="icon-market" ></i><?php echo $this->__('Add to Cart') ?></a>
                                <a href="<?php echo $product->getProductUrl(); ?>" class="featured-quick-view"><i class="icon-search"></i>Quick View</a>
							</div>
                            
                            <div class="prod-info">
                            	<h2 class="prod-name"><?php echo $product->getName(); ?></h2>
                                <div class="price-box">
								<?php echo Mage::helper('core')->currency($product->getFinalPrice(),true,true); ?>
<?php if($product->getMsrp() !=''): ?>
  /<span class="old-price"><?php echo Mage::helper('core')->currency($product->getMsrp(),true,true); ?></span>
  <?php endif;?>



								</div>
                            </div>
                         </div>   
                    </div>
                    <?php
						}
					?>
                </div>
            </div>
        </div>
    </div>
</section>         


<section id="brands" class="carousal-container">
	<div class="container">
    	<div class="row">
        	<div class="col-sm-12">
            	<div class="featured-heading" style="padding-top:0; margin-top:0px; margin-bottom:20px; ">
                    <div class="featured-title" style="border-bottom:1px solid #efefef; padding:15px 0">
                      <h1 ><img src="<?php echo $this->getSkinUrl('images/hot-icon.png'); ?>" style="top:8px;"> Shop By Brands</h1>
                    </div>
                </div>
            	<div class="featuredList owl-carousel">
                	<?php

						// Gets all sub categories of parent category 'Brands'
						$parent = Mage::getModel('catalog/category')->load(53);
						
						// Create category collection for children
						$childrenCollection = $parent->getCollection();
						// Only get child categories of parent cat
						$childrenCollection->addIdFilter($parent->getChildren());
						// Only get active categories
						$childrenCollection->addAttributeToFilter('is_active', 1);
						
						// Add base attributes
						$childrenCollection->addAttributeToSelect('url_key')
						->addAttributeToSelect('shop_brand_logo')
						->addAttributeToSelect('all_children')
						->addAttributeToSelect('is_anchor')
						->setOrder('position', Varien_Db_Select::SQL_ASC)
						->joinUrlRewrite();
						
						// ADD IMAGE ATTRIBUTE
						$childrenCollection->addAttributeToSelect('image');
						$count=1;
						foreach($childrenCollection as $cat):
						$_file_name = $cat->getShopBrandLogo(); // Here $cat is category data array
						$_media_dir = Mage::getBaseDir('media') . DS . 'catalog' . DS . 'category' . DS;
						$cache_dir = $_media_dir . DS; // Here i create a resize folder. for upload new category image
						
						if (file_exists($cache_dir . $_file_name)) {
						$catImg =Mage::getBaseUrl('media') .  'catalog' . DS . 'category' . DS . $_file_name;
						} elseif (file_exists($_media_dir . $_file_name)) {
						if (!is_dir($cache_dir)) {
						mkdir($cache_dir);
						}
						
						$_image = new Varien_Image($_media_dir . $_file_name);
						$_image->resize(101, 106); // change image height, width
						$_image->save($cache_dir . $_file_name);
						$catImg = Mage::getBaseUrl('media') . 'catalog' . DS . 'category' . DS . $_file_name;
						}
?>
                            <div class="item text-center">
                            <a href="<?php echo $cat->getURL(); ?>"><img src="<?php echo $catImg; ?>" class="img-responsive"/></a>
                            </div>
						<?php endforeach; ?>
                	
                    
                </div>
            </div>
        </div>
        
        
        
    </div>	
</section> 

<section id="testimonials">
	<div class="container">
    	<div class="row">
        	<div class="col-sm-12">
            
            	<div class="featured-heading" style="padding-top:0; margin-top:0px; margin-bottom:20px; ">
                    <div class="featured-title">
                      <h1 ><img src="<?php echo $this->getSkinUrl('images/homepage/customer_feedback_icon.png'); ?>" style="top:8px;"> Customers Feedback</h1>
                    </div>
                </div>
            
 
                <div class="cutomer_feedback">
                  <?php  $feedbackData = Mage::getModel('customerfeedback/customerfeedback')->getCollection()->addFieldToFilter('approved',1)->getLastItem()->getData();
                //  echo "<pre>";print_r($feedbackData);exit;
                  if(!empty($feedbackData)):
                  $feedbackcustomerName = $feedbackData['customer_name'];
                  $feedback= $feedbackData['feedback'];
                  $postedDate= $feedbackData['posted_date'];
                  ?>
            
                  <p>“<?php echo $feedback;?>”</p>
                    <h4><?php echo $feedbackcustomerName;?> <span>- <?php echo date("F, Y",strtotime($postedDate));?></span></h4>
            
                  <?php endif;?>
            
                </div>

            </div><!--end col-sm-12-->
        </div>
    </div>
</section>
               
<script type="text/javascript">

jQuery().ready(function(){
	jQuery('.owl-carousel').owlCarousel({
    loop:true,
    margin:15,
	autoplay:true,
    autoplayTimeout:6000,
    autoplayHoverPause:true,
    responsiveClass:true,
	navText:['<img src="/media/atlas_banner/default/prew.png">','<img src="/media/atlas_banner/default/next.png">'],
    responsive:{
        0:{
            items:2,
            nav:true,
			loop:true
        },
        600:{
            items:3,
            nav:true,
			loop:true
        },
        1000:{
            items:5,
            nav:true,
            loop:true
        }
    }
})
})


</script>









