<div class="std">
<section class="container sell_on_ziwira_section">
      <form action="<?php echo Mage::getUrl('customerfeedback/index/save',array('_secure'=>true))?>" method="post" >
    <div class="left-checkout-section">
        <h2>Customer Feedback</h2>
        <div class="login-section">
              <div class="sell-form-control">
                <label>Customer Name <span>*</span></label>
                  <input required type="text" name="customer-name"placeholder="" />
              </div>
              <div class="sell-form-control">
                <label>Feedback Description<span>*</span></label>
                  <textarea required name="feedback-desc"></textarea>
</div>
 <input type="submit" class="sign-in-checkout-btn btn" value="SUBMIT"/>     
 </div>
    </div>
    </form>

</section>
</div>
