<div class="white-bg clearall">
  <div class="main-container" id="maincontent">
    <div class="main">
                <div class="col-main">
                  <div class="home-top">


<div class="clearall home-container-1">
  <div class="home-container-left pull-leftada">
    <div class=" col-md-12" >
      <!-- Page Content -->
          <div id="page-content-wrapper" class="graybg">
            <section class="container-fluid ">

            <div class="page404 row">
                <div class="errorsec "  >
                	<div class="leftarea col-md-6">
                  	<h2> 404 <span>Error</span></h2>
                  </div>

                  <div class="rightarea col-md-6">
                  	<p>We can’t find the page you're looking for.</p>
                    <a href="https://ziwirastore.com/" class="backtohome"> Go to Home Page</a>
                  </div>

                </div>


            <div class="content-area col-md-12">
           	<h3>WHOOPS, OUR BAD...</h3>

            <p><strong>The page you requested was not found, and we have a fine guess why.</strong></p>
<ul>
<li> 	<em>If you typed the URL directly, please make sure the spelling is correct.</em></li>
<li><em> If you clicked on a link to get here, the link is outdated.</em></li>
</ul>
<p><strong> What can you do?</strong>
</p>
<p> <strong>Have no fear, help is near! There are many ways you can get back on track with Ziwira Store.</strong></p>
<ul>
<li><a href="#https://ziwirastore.com/"> <strong>	Go back</strong></a> to the previous page.</li>
<li> 	Use the search bar at the top of the page to search for your products.</li>
<li> 	Follow these links to get you back on track!</li>
<li><a href="https://ziwirastore.com/"> <strong>Store Home</strong></a> | <a href="#"><strong>My Account</strong></a><br>
</li>
</ul>
</div>

            </div>

            </section>
                        </div>
          <!-- /#page-content-wrapper -->
    </div>
  </div>




</div>
                </div>
    </div>
  </div>

</div>
