<?php
/**
 * lotusbreath
 */
?>
<?php
    $relatedLocationFields = Mage::getStoreConfig("lotusbreath_onestepcheckout/general/location_fields");
    if ($relatedLocationFields){
        $relatedLocationFields = explode(',',$relatedLocationFields);
    }else{
        $relatedLocationFields = array('postcode', 'country_id', 'region_id','city');
    }
    $isAllowGuest = Mage::helper('checkout')->isAllowedGuestCheckout(Mage::getSingleton('checkout/session')->getQuote());
    $isCheckEmailExists = false;
    if (!$isAllowGuest && !Mage::getSingleton('customer/session')->isLoggedIn())
        $isCheckEmailExists = true;
?>

<div style="color:red;" id="billing-error" class="error"></div>

    
        <?php if ($this->customerHasAddresses()): ?>
           
                <p ><?php echo $this->__('Select a billing address from your address book or enter a new address.') ?></p>

                <div class="form-group">
                    <?php echo $this->getAddressesHtmlSelect('billing') ?>
                    <script>
                    jQuery().ready(function(){
                    	jQuery("select#billing-address-select").addClass("form-control");
                   	})
					</script>
                </div>
           
        <?php endif; ?>
        <div id="billing-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif; ?>>
           
                <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>"
                       id="billing:address_id"/>
               

                   
                        <?php if (!$this->isCustomerLoggedIn()): ?>
							<div class="form-group">
                            	<label for="billing:email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>

                           
                                <input type="text" name="billing[email]" id="billing:email"
                                       value="<?php echo $this->escapeHtml($this->getAddress()->getEmail()) ?>"
                                       title="<?php echo $this->__('Email Address') ?>"
                                       data-validate="{required:true, 'validate-email':true }"
                                       class="form-control validate-email required-entry <?php echo $isCheckEmailExists ? 'check-email-exists' : '';?>"/>
                            </div>

                        <?php endif; ?>
                   
                    <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getAddress()->getFirstname() ? $this->getAddress() : $this->getQuote()->getCustomer())->setForceUseCustomerRequiredAttributes(!$this->isCustomerLoggedIn())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                    <?php if ($isAllowGuest):
                      if(!Mage::getSingleton('customer/session')->isLoggedIn()):
                      ?>

                        <div class="checkbox">
                        	<label>
                            	<input type="checkbox" name="billing[create_new_account]"
                                   value=1/> <?php echo $this->__("Register new account"); ?>?
                           </label>        
                        </div>
                      <?php endif;?>
                    <?php else: ?>
                        <p><strong><?php echo $this->__("Register new account - Enter your password:"); ?></strong></p>
                    <?php endif; ?>
                    <?php $passwordLiId = $isAllowGuest ? 'register-customer-password' : ''; ?>
                    <div id="<?php echo $passwordLiId;?>">
                        <div class="form-group">
                            <label for="billing:customer_password"
                                   class="required"><em>*</em><?php echo $this->__('Password') ?></label>

                            
                                <input type="password" name="billing[customer_password]"
                                       id="billing:customer_password" title="<?php echo $this->__('Password') ?>"
                                       class="form-control required-entry validate-password"/>
                            
                        </div>
                        <div class="form-group">
                            <label for="billing:confirm_password"
                                   class="required"><em>*</em><?php echo $this->__('Confirm Password') ?></label>

                           
                                <input type="password" name="billing[confirm_password]"
                                       title="<?php echo $this->__('Confirm Password') ?>"
                                       id="billing:confirm_password"
                                       class="form-control required-entry validate-cpassword"/>
                            
                        </div>
                    </div>
                    <?php if (Mage::getStoreConfig('lotusbreath_onestepcheckout/billingaddress/allowshowcompanyfield')): ?>
                    <div class="form-group">
                                <label for="billing:company"><?php echo $this->__('Company') ?></label>

                               
                                    <input type="text" id="billing:company" name="billing[company]"
                                           value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>"
                                           title="<?php echo $this->__('Company') ?>"
                                           class="form-control <?php echo $this->helper('lotusbreath_onestepcheckout')->getAttributeValidationClass('company') ?>"/>
                    </div>
					<?php endif; ?>
                    <?php $_streetValidationClass = $this->helper('lotusbreath_onestepcheckout')->getAttributeValidationClass('street'); ?>
                   <div class="form-group">
                        <label for="billing:street1" class="required"><em>*</em><?php echo $this->__('Address') ?>

                        </label>

                        
                            <input type="text" title="<?php echo $this->__('Street Address') ?>"
                                   name="billing[street][]" id="billing:street1"
                                   value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>"
                                   class="form-control <?php echo $_streetValidationClass ?>"/>
                       
                    </div>
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                        <div class="form-group">
                            
                                <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>"
                                       name="billing[street][]" id="billing:street<?php echo $_i ?>"
                                       value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>"
                                       class="form-control <?php echo $_streetValidationClass ?>"/>
                           
                        </div>
                    <?php endfor; ?>
                    <?php
                    $isShowVATNumber = Mage::getStoreConfig('lotusbreath_onestepcheckout/billingaddress/allowshowvatnumberfield');
                    if ($isShowVATNumber && $this->helper('lotusbreath_onestepcheckout')->isVatAttributeVisible()) :
                    //if ($isShowVATNumber):
                    ?>

                        <div class="form-group">
                            
                            <label for="billing:vat_id" class="required">
                                <em>*</em>
                                <?php echo $this->__('VAT Number') ?></label>
                            
                                <input type="text" id="billing:vat_id" name="billing[vat_id]"
                                       value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>"
                                       title="<?php echo $this->__('VAT Number') ?>"
                                       class="form-control <?php echo $this->helper('lotusbreath_onestepcheckout')->getAttributeValidationClass('vat_id') ?>"/>
                            
                           
                        </div>
                    <?php endif; ?>
                     <div class="row">
                        <div class="form-group col-sm-6">
                            <?php
                            $changeLocationClass = '';
                            if (in_array('city', $relatedLocationFields))
                                $changeLocationClass = 'change_location_field';
                            ?>
                            <label for="billing:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>

                           
                                <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]"
                                       value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"
                                       class="<?php echo $changeLocationClass;?> form-control <?php echo $this->helper('lotusbreath_onestepcheckout')->getAttributeValidationClass('city') ?>"
                                       id="billing:city"/>
                            
                        </div>
                        
                       
                        <div class="form-group col-sm-6">

                            <label for="billing:region_id"
                                   class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>

                            
                                <?php
                                $changeLocationClass = '';

                                if (in_array('region_id', $relatedLocationFields))
                                    $changeLocationClass = 'change_location_field';
                                ?>
                                <select id="billing:region_id" name="billing[region_id]"
                                        title="<?php echo $this->__('State/Province') ?>" class="form-control validate-select <?php echo $changeLocationClass;?>"

                                        style="display:none;"
                                        <?php if (Mage::getStoreConfig('general/region/display_all') == false):?>disabled="disabled"<?php endif; ?>
                                    >
                                    <option
                                        value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                </select>
                                <script type="text/javascript">
                                    //<![CDATA[
                                    $('billing:region_id').setAttribute('defaultValue', "<?php echo $this->getAddress()->getRegionId() ?>");
                                    //]]>
                                </script>
                                <input type="text" id="billing:region" name="billing[region]"
                                       value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>"
                                       title="<?php echo $this->__('State/Province') ?>"
                                       class=" <?php echo $changeLocationClass;?> input-text <?php echo $this->helper('lotusbreath_onestepcheckout')->getAttributeValidationClass('region') ?>"
                                       style="display:none;"
                                       <?php if (Mage::getStoreConfig('general/region/display_all') == false):?>disabled="disabled"<?php endif; ?>
                                    />
                            
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-sm-6">
                            <label for="billing:postcode"
                                   class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>

                            
                                <?php
                                $changeLocationClass = '';
                                if (in_array('postcode', $relatedLocationFields))
                                    $changeLocationClass = 'change_location_field';
                                ?>
                                <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>"
                                       name="billing[postcode]" id="billing:postcode"
                                       value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>"
                                       class="<?php echo $changeLocationClass; ?> form-control validate-zip-international <?php echo $this->helper('lotusbreath_onestepcheckout')->getAttributeValidationClass('postcode') ?>"/>
                           
                        </div>
                        <div class="form-group col-sm-6">
                            <label for="billing:country_id"
                                   class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                           
                                <?php echo $this->getCountryHtmlSelect('billing') ?>
                            
                            <?php
                            $changeLocationClass = '';
                            if (in_array('country_id', $relatedLocationFields)):
                                $changeLocationClass = 'change_location_field';

                            ?>
                            <script>
                                var billingCountry = document.getElementById("billing:country_id");
                                billingCountry.setAttribute('class', billingCountry.getAttribute('class') + ' <?php echo $changeLocationClass;?> form-control');

                            </script>
                            <?php endif;?>
                            <?php
                            $changeLocationClass = '';
                            if (in_array('region_id', $relatedLocationFields)):
                                $changeLocationClass = 'update-location-region-class';
                            ?>
                            <script>
                                var billingCountry = document.getElementById("billing:country_id");
                                billingCountry.setAttribute('class', billingCountry.getAttribute('class') + ' <?php echo $changeLocationClass;?>');

                            </script>
                            <?php endif;?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-sm-6">
                            <label for="billing:telephone"
                                   class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>

                            
                                <input type="text" name="billing[telephone]"
                                       value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>"
                                       title="<?php echo $this->__('Telephone') ?>"
                                       class="form-control <?php echo $this->helper('lotusbreath_onestepcheckout')->getAttributeValidationClass('telephone') ?>"
                                       id="billing:telephone"/>
                            
                        </div>
                        <?php if (Mage::getStoreConfig('lotusbreath_onestepcheckout/billingaddress/allowshowfaxfield')): ?>
                            <div class="form-group col-sm-6">
                                <label for="billing:fax"><?php echo $this->__('Fax') ?></label>

                                
                                    <input type="text" name="billing[fax]"
                                           value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>"
                                           title="<?php echo $this->__('Fax') ?>"
                                           class="form-control <?php echo $this->helper('lotusbreath_onestepcheckout')->getAttributeValidationClass('fax') ?>"
                                           id="billing:fax"/>
                                
                            </div>
                        <?php endif; ?>
                    </div>
                    <?php if (!$this->isCustomerLoggedIn()): ?>

                        <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                        <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
                        <?php if ($_dob->isEnabled() || $_gender->isEnabled()): ?>
                            <li class="fields form-control">
                                <?php if ($_dob->isEnabled()): ?>
                                    <div class="field">
                                        <?php echo $_dob->setDate($this->getQuote()->getCustomerDob())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                                    </div>
                                <?php endif; ?>
                                <?php if ($_gender->isEnabled()): ?>
                                    <div class="field">
                                        <?php echo $_gender->setGender($this->getQuote()->getCustomerGender())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                                    </div>
                                <?php endif ?>
                            </li>
                        <?php endif ?>

                        <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                        <?php if ($_taxvat->isEnabled()): ?>
                            <li>
                                <?php echo $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?>
                            </li>
                        <?php endif ?>

                    <?php endif; ?>
                    <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()): ?>
                        <div class="checkbox"> 
                        <label
                                for="billing:save_in_address_book">
                            <input type="checkbox" name="billing[save_in_address_book]" value="1"
                                   title="<?php echo $this->__('Save in address book') ?>"
                                   id="billing:save_in_address_book"
                                   onchange="if(window.shipping) shipping.setSameAsBilling(false);"<?php if ($this->getAddress()->getSaveInAddressBook()): ?> checked="checked"<?php endif; ?>
                                   class="checkbox"/>
                           <?php echo $this->__('Save in address book') ?></label>
                        </div>
                    <?php else: ?>
                        <div class="hidden"><input type="hidden" name="billing[save_in_address_book]" value="1"/>
                        </div>
                    <?php endif; ?>
                    <?php echo $this->getChildHtml('form.additional.info'); ?>
                
            
        </div>
        <?php /* Extensions placeholder */ ?>
        <?php echo $this->getChildHtml('checkout.onepage.billing.extra') ?>
        <?php
            $alwaysusesameasbilling = Mage::getStoreConfig('lotusbreath_onestepcheckout/shippingaddress/alwaysusesameasbilling');
        ?>
        <?php if ($this->canShip() && $alwaysusesameasbilling == false): ?>
            <div class="radio">
            	<label
                    for="billing:use_for_shipping_yes">
                <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_yes"
                       value="1"<?php if ($this->isUseBillingAddressForShipping()) { ?> checked="checked"<?php } ?>
                       title="<?php echo $this->__('Ship to this address') ?>"
                        class="radio"/><?php echo $this->__('Ship to this address') ?></label></div>
            <div class="radio">
            <label
                    for="billing:use_for_shipping_no">
                <input type="radio" name="billing[use_for_shipping]" id="billing:use_for_shipping_no"
                       value="0"<?php if (!$this->isUseBillingAddressForShipping()) { ?> checked="checked"<?php } ?>
                       title="<?php echo $this->__('Ship to different address') ?>"
                        class="radio"/><?php echo $this->__('Ship to different address') ?></label>
            </div>
        <?php endif; ?>
   
    <?php if (!$this->canShip() || $alwaysusesameasbilling == true): ?>
        <input type="hidden" name="billing[use_for_shipping]" value="1"/>
    <?php endif; ?>


<script type="text/javascript">
    //<![CDATA[
    var billing = new Billing();

</script>
