<?php if (!Mage::helper('customer')->isLoggedIn()) : ?>
    <form class="white-popup mfp-hide" id="loginFrm"
          action="<?php echo $this->getUrl('onestepcheckout/account/login') ?>" method="POST"
        >
        <h3><?php echo $this->__("Login"); ?></h3>

        <p class="mage-error" id="loginFrmErrMsg"></p>

        <p class="mage-success success" id="loginFrmSuccessMsg"></p>
        
            
                <div class="form-group">
                    
                        <label for="login-email"><?php echo $this->__("Email"); ?><em>*</em></label>
                        <input type="text" class="form-control required-entry validate-email" id="login-email"
                               name="login[username]" value="">
                 </div>   
                
                    <div class="form-group">
                        <label for="login-password"><?php echo $this->__("Password"); ?><em>*</em></label>
                        <input type="password" class="form-control required-entry" id="login-password"
                               name="login[password]">
                    </div>
                
            
           <br />
<br />

                <p >
                    <a id="loginFrmForgotLink" href="<?php echo Mage::getUrl("customer/account/forgotpassword/"); ?>"
                       class="f-left">
                        <?php echo $this->__("Forgot your password?"); ?></a>
                        
                        <button type="submit" class="btn btn-success pull-right">Login</button>
                        
                </p>
                
           		<div class="clearfix"></div>
        
    </form>

    <form class="white-popup mfp-hide form-popup" id="forgotFrm"
          action="<?php echo $this->getUrl('onestepcheckout/account/forgotpasswordpost') ?>" method="post">

        <h3><?php echo $this->__('Retrieve your password here') ?></h3>

        <p class="mage-error" id="forgotFrmErrMsg"></p>

        <p class="mage-success success" id="forgotFrmSuccessMsg"></p>

        <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
       
            
                <div class="form-group">
                    <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?>
                    </label>

                    
                        <input type="email" name="email" alt="email" id="email_address"
                               class="form-control required-entry validate-email"
                               value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>"/>
                    
                </div>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
           
            <br />
<br />

                <p>
                    <a class="login_link" id="forgotBackLoginLink"
                       href="<?php echo $this->helper('customer')->getLoginUrl() ?>">
                        <small>&laquo; </small><?php echo $this->__('Back to Login') ?></a>
                        <button type="submit" title="<?php echo $this->__('Submit') ?>" class="btn btn-primary pull-right">
                    <?php echo $this->__('Submit') ?></button>
                </p>
                
           <div class="clearfix"></div>
        

    </form>

<?php endif; ?>
