<?php
/**
 * Lotusbreath
 */
?>
<?php
$relatedLocationFields = Mage::getStoreConfig("lotusbreath_onestepcheckout/general/location_fields");
if ($relatedLocationFields){
    $relatedLocationFields = explode(',',$relatedLocationFields);
}else{
    $relatedLocationFields = array('postcode', 'country_id', 'region_id','city');
}

$isShortShippingAddressInfo = Mage::getStoreConfig('lotusbreath_onestepcheckout/shippingaddress/useshortshippingaddress');

?>
<div style="color:red;" id="shipping-error" class="error"></div>


   
        <?php if ($this->customerHasAddresses()): ?>
          
                <p for="shipping-address-select"><?php echo $this->__('Select a shipping address from your address book or enter a new address.') ?></p>
                <div class="form-group">
                    <?php echo $this->getAddressesHtmlSelect('shipping') ?>
                    <script>
                    jQuery().ready(function(){
                    	jQuery("select#shipping-address-select").addClass("form-control");
                   	})
					</script>
                </div>
           
        <?php endif ?>
        <div id="shipping-new-address-form"<?php if ($this->customerHasAddresses()): ?> style="display:none;"<?php endif ?>>
            
                <input type="hidden" name="shipping[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="shipping:address_id" />
                
                    <?php if(!$isShortShippingAddressInfo):?>
                    <?php echo $this->getLayout()->createBlock('Mage_Customer_Block_Widget_Name')->setObject($this->getAddress())->setFieldIdFormat('shipping:%s')->setFieldNameFormat('shipping[%s]')->toHtml() ?>
                    <?php if( Mage::getStoreConfig('lotusbreath_onestepcheckout/shippingaddress/allowshowcompanyfield') ):?>
                    
                        <div class="form-group">
                            <label for="shipping:company"><?php echo $this->__('Company') ?></label>
                            
                                <input type="text" id="shipping:company" name="shipping[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="form-control <?php echo $this->helper('lotusbreath_onestepcheckout')->getAttributeValidationClass('company') ?>" />
                            
                        </div>
                    
                    <?php endif;?>
                    <?php endif;?>
                    <?php $_streetValidationClass = $this->helper('lotusbreath_onestepcheckout')->getAttributeValidationClass('street'); ?>
                    <div class="form-group>">
                        <label for="shipping:street1" class="required"><em>*</em><?php echo $this->__('Address') ?></label>
                        
                            <input type="text" title="<?php echo $this->__('Street Address') ?>" name="shipping[street][]" id="shipping:street1" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet(1)) ?>" class="form-control <?php echo $_streetValidationClass ?>" />
                       
                    </div>
                    <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                    <?php for ($_i = 2, $_n = $this->helper('customer/address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                        
                            <div class="form-group">
                                <input type="text" title="<?php echo $this->__('Street Address %s', $_i) ?>" name="shipping[street][]" id="shipping:street<?php echo $_i ?>" value="<?php echo $this->escapeHtml($this->getAddress()->getStreet($_i)) ?>" class="form-control <?php echo $_streetValidationClass ?>" />
                            </div>
                        
                    <?php endfor; ?>

                    <?php
                    $isShowVATNumber = Mage::getStoreConfig('lotusbreath_onestepcheckout/shippingaddress/allowshowvatnumberfield');
                    if ($isShowVATNumber && $this->helper('lotusbreath_onestepcheckout')->isVatAttributeVisible()) : ?>
                        <div class="form-group">
                            <label for="billing:vat_id"><?php echo $this->__('VAT Number'); ?></label>
                            
                                <input type="text" id="shipping:vat_id" name="shipping[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()); ?>" title="<?php echo $this->__('VAT Number'); ?>" class="form-control <?php echo $this->helper('lotusbreath_onestepcheckout')->getAttributeValidationClass('vat_id') ?>" />
                            
                        </div>
                    <?php endif; ?>
                    <div class="row">
                        <div class="form-group col-sm-6">

                            <label for="shipping:city" class="required"><em>*</em><?php echo $this->__('City') ?></label>
                            
                                <?php
                                $changeLocationClass = '';
                                if (in_array('city', $relatedLocationFields))
                                    $changeLocationClass = 'change_location_field';
                                ?>
                                <input type="text" title="<?php echo $this->__('City') ?>" name="shipping[city]" value="<?php echo $this->escapeHtml($this->getAddress()->getCity()) ?>"
                                       class="form-control <?php echo $changeLocationClass;?>  <?php echo $this->helper('lotusbreath_onestepcheckout')->getAttributeValidationClass('city') ?>" id="shipping:city" />
                            
                        </div>
                        <div class="form-group col-sm-6">
                            <label for="shipping:region" class="required"><em>*</em><?php echo $this->__('State/Province') ?></label>
                            <?php
                            $changeLocationClass = '';

                            if (in_array('region_id', $relatedLocationFields))
                                $changeLocationClass = 'change_location_field';
                            ?>
                           
                                <select id="shipping:region_id" name="shipping[region_id]" title="<?php echo $this->__('State/Province') ?>"
                                        class="form-control validate-select <?php echo $changeLocationClass;?>" style="display:none;">
                                    <option value=""><?php echo $this->__('Please select region, state or province') ?></option>
                                </select>
                                <input type="text" id="shipping:region" name="shipping[region]" value="<?php echo $this->escapeHtml($this->getAddress()->getRegion()) ?>" title="<?php echo $this->__('State/Province') ?>"
                                       class="form-control <?php echo $changeLocationClass;?> <?php echo $this->helper('lotusbreath_onestepcheckout')->getAttributeValidationClass('region') ?>" style="display:none;" />
                            
                        </div>
                   </div>
                    <div class="row">
                        <div class="form-group col-sm-6">
                            <label for="shipping:postcode" class="required"><em>*</em><?php echo $this->__('Zip/Postal Code') ?></label>
                            
                                <?php
                                $changeLocationClass = '';
                                if (in_array('postcode', $relatedLocationFields))
                                    $changeLocationClass = 'change_location_field';
                                ?>
                                <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="shipping[postcode]" id="shipping:postcode" value="<?php echo $this->escapeHtml($this->getAddress()->getPostcode()) ?>"
                                       class="<?php echo $changeLocationClass;?>  form-control validate-zip-international <?php echo $this->helper('lotusbreath_onestepcheckout')->getAttributeValidationClass('postcode') ?>" />
                            
                        </div>
                        <div class="form-group col-sm-6">
                            <label for="shipping:country_id" class="required"><em>*</em><?php echo $this->__('Country') ?></label>
                            
                                <?php echo $this->getCountryHtmlSelect('shipping') ?>
                            
                            <?php
                            $changeLocationClass = '';
                            if (in_array('country_id', $relatedLocationFields)):
                                $changeLocationClass = 'change_location_field';

                                ?>
                                <script>
                                    var billingCountry = document.getElementById("shipping:country_id");
                                    billingCountry.setAttribute('class', billingCountry.getAttribute('class') + ' <?php echo $changeLocationClass;?>');

                                </script>
                            <?php endif;?>
                            <?php
                            $changeLocationClass = '';
                            if (in_array('region_id', $relatedLocationFields)):
                                $changeLocationClass = 'update-location-region-class';
                                ?>
                                <script>
                                    var billingCountry = document.getElementById("shipping:country_id");
                                    billingCountry.setAttribute('class', billingCountry.getAttribute('class') + ' <?php echo $changeLocationClass;?> form-control');

                                </script>
                            <?php endif;?>
                        </div>
                    </div>
                    <div class="row">
                        <div class="form-group col-sm-6">
                            <label for="shipping:telephone" class="required"><em>*</em><?php echo $this->__('Telephone') ?></label>
                           
                                <input type="text" name="shipping[telephone]" value="<?php echo $this->escapeHtml($this->getAddress()->getTelephone()) ?>" title="<?php echo $this->__('Telephone') ?>" class="form-control <?php echo $this->helper('lotusbreath_onestepcheckout')->getAttributeValidationClass('telephone') ?>" id="shipping:telephone" />
                            
                        </div>
                        <?php if (Mage::getStoreConfig('lotusbreath_onestepcheckout/shippingaddress/allowshowfaxfield')): ?>
                        <div class="form-group col-sm-6">
                            <label for="shipping:fax"><?php echo $this->__('Fax') ?></label>
                            
                                <input type="text" name="shipping[fax]" value="<?php echo $this->escapeHtml($this->getAddress()->getFax()) ?>" title="<?php echo $this->__('Fax') ?>" class="form-control <?php echo $this->helper('lotusbreath_onestepcheckout')->getAttributeValidationClass('fax') ?>" id="shipping:fax" />
                            
                        </div>
                        <?php endif;?>
                    </div>
                    <?php if ($this->isCustomerLoggedIn() && $this->customerHasAddresses()):?>
                        <div class="checkbox">
                        <label for="shipping:save_in_address_book">
                            <input type="checkbox" name="shipping[save_in_address_book]" value="1" title="<?php echo $this->__('Save in address book') ?>" id="shipping:save_in_address_book" <?php if ($this->getAddress()->getSaveInAddressBook()):?> checked="checked"<?php endif;?> class="checkbox" /><?php echo $this->__('Save in address book') ?></label></div>
                    <?php else:?>
                      <input type="hidden" name="shipping[save_in_address_book]" value="1" />
                    <?php endif;?>
               
        </div>

   
    

<script type="text/javascript">

</script>
