<div class="white-bg clearall">
  <div class="main-container" id="maincontent">
    <div class="main">
                <div class="col-main">
<div class="clearall home-container-1">
  <div class="home-container-left pull-leftada">
<div class="clearall" style="width:1273px">
    <!-- Page Content -->
          <div id="page-content-wrapper" class="graybg" style="width: 90%;padding: 0px;float: none;margin: 0 auto;">
            <section class="container-fluid ">

            <div class="logout-sec">
                  <h2> Your are now logged out </h2>


<div class="sub-heading">

<p>You have logged out and will be redirected to our homepage in 5 seconds</p>

          </div>
          <script type="text/javascript">
          //<![CDATA[
              setTimeout(function(){ location.href = '<?php echo $this->getUrl() ?>'},5000);
          //]]>
          </script>
          <!-- /#page-content-wrapper -->
    </div>
  </div>




</div>
                </div>
    </div>
  </div>

</div>
