<!-- Categories display start -->

<?php
/*
Author Name: Firasath
Author URI: http://www.firasath.com
Author Email: firasath_hussain20@yahoo.com
*/
$_helper = Mage::helper('catalog/category');
$_categories = $_helper->getStoreCategories();
if (count($_categories) > 0){ ?>

  <ul class="nav navbar-nav">
    <?php  foreach($_categories as $_category){
          $_category = Mage::getModel('catalog/category')->load($_category->getId());
          $_subcategories = $_category->getChildrenCategories();
          if($_category->getIsActive() == 1 & $_category->getIncludeInMenu() == 1){
          if (count($_subcategories) > 0 || $_category->getUrlKey() == 'sales'){ ?>
              <li class="dropdown mega-dropdown">
                <a href="<?php echo $_category->getUrl(); ?>"><?php echo $_category->getName(); ?></a>
				
				<div class="dropdown-menu mega-dropdown-menu">
					<div class="row">
						<div class="col-sm-9">
							<div class="row">
							<?php 
									$count==0;
									$closingTag=false;
									foreach($_subcategories as $_subcategory)
									{
										if($count%4==0)
										{
											$count++;
											$closingTag=true;
							?>
											<div class="col-sm-4">	
												<ul>	
							<?php				
										}
							          				$_subcategory = Mage::getModel('catalog/category')->load($_subcategory->getEntityId());
							?>
												<?php if($_subcategory->getIsActive() == 1 && $_subcategory->getIncludeInMenu() ==1)
												{?>
													<li><a href="<?php echo $_subcategory->getUrl(); ?>"><?php echo $_subcategory->getName(); ?></a></li>
												  <?php 
												 }
										if($count==4)
										{
											$count=0;
											$closingTag=false;	
							?>				
												</ul>
											</div>	
												
							<?php				
										}
												  
									} 
									
									if($closingTag)
									{
							?>
											</ul>
										</div>	
							<?php				
									}
							?>
							</div>
							
							
							<div class="row">
								<div class="col-sm-4 text-center">
									<a href="https://ziwirastore.com/shop-by-brand/prairie-naturals.html"><img src="<?php echo $this->getSkinUrl('images/homepage/menu-icon-3.png');?>" alt="Prairie Naturals" class="img-responsive" /></a>
								</div>
								
								<div class="col-sm-4 text-center">
									<a href="https://ziwirastore.com/shop-by-brand/organika.html"><img src="<?php echo $this->getSkinUrl('images/homepage/menu-icon-2.png');?>" alt="Organika"  class="img-responsive" /></a>
								</div>
								
								<div class="col-sm-4 text-center">
									<a href="https://ziwirastore.com/shop-by-brand/now-foods.html"><img src="<?php echo $this->getSkinUrl('images/homepage/menu-icon-1.png');?>" alt="Now" class="img-responsive" /></a>
								</div>
								
							</div>
							
						</div>
						
						<div class="col-sm-3 grayBox">
							<h3>ON SALE</h3>
							<ul>
							  <li><a href="https://ziwirastore.com/garcinia-plus.html">Get 26% Off on Weight Loss Products</a></li>
							  <li><a href="https://ziwirastore.com/health-beauty/bath-body/big-sky-tea-tree-shampoo.html">Get 17% Off on Big Sky Tea Tree Shampoo</a></li>
							  <li><a href="https://ziwirastore.com/hair-plus.html">Get 27% Off on Hair Plus - Gives you Hair </a></li>
							</ul>
							<h3>FEATURED</h3>
							<ul>
								<li><a href="https://ziwirastore.com/coenzyme-q10-w-vit-e-a.html">Anti-aging</a></li>
							</ul>
						</div>
						
					</div>
					
				</div>
				
				
                

              </li>

          <?php }
     }
      } ?>


    </ul>

<?php
}
?>
