<?php 
/**
 * @category    Development
 * @package     Singsys_Fbconnect
 * @version     1.0.0
 * @copyright   Copyright (c) 2015 SingsysShop (https://www.singsys.com)
 * @author	Singsys
 */
?>

<div class="clearer">
    <div class="singsys-fbconnect-facebooks">
        <div class="singsys-fbconnect-facebook-inners">
            <a href="<?php echo $this->escapeUrl($this->_getButtonUrl()); ?>"><img style="margin: 0 auto;" src="<?php echo $this->getSkinUrl('images/fb.png'); ?>"/></a>
        </div>
        <div class="singsys-fbconnect-facebook-right"></div>
    </div>
</div>
