<div class="white-bg clearall">
  <div class="main-container" id="maincontent">
    <div class="main">
                <div class="col-main">
                  <div class="home-top hidden">

  <div class="home-top-left">
    <div class="home-heading pull-left">
      <h1><i class="icon-market"></i>marketplace</h1>
    </div>
    <div class="returns-block pull-left">
      <a href=""><img class="pull-left" src="<?php echo $this->getSkinUrl('images/return.png'); ?>"/><span class="pull-left">Return and Refund Policies</span><span class="pull-left"></span></a>
    </div>
     <div class="returns-block payments-block pull-left">
      <a href="<?php echo Mage::getBaseUrl().'tax-regulation' ?>">
      <img class="pull-left" src="<?php echo $this->getSkinUrl('images/payment-option.png'); ?>"/><span class="pull-left">Tax<br/>Regulation</span><span class="pull-left"></span></a>
    </div>
  </div>

  <div class="home-top-right pull-right">
    <ul>
      <li><span class="curr">currency</span></li>
      <li>your marketplace</li>
      <li>view cart/li>
    </ul>
  </div>
</div>

<div class="clearall home-container-1">
  <div class="home-container-left pull-leftada">
    <div class="store-search">
      <form>
        <div class="input-group">
                      <input type="text" name="q" id="q" class="form-control" autocomplete="off" placeholder="What are you looking for?">
                      <button class="btn btn-default" type="submit">
                              <i class="icon-search"></i>
                              <span class="i-name">Search</span>
                          </button>
                  </div>
      </form>
    </div>
    <div class="clearall" style="width:1273px">
      <div class="home-left-col pull-left">
        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('head-cat')->toHtml(); ?>
        <div class="recycle-block">
          <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('green-products')->toHtml(); ?>
        </div>
        <div class="recycle-block">
          <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('express-delivery')->toHtml(); ?>
        </div>

      </div>
      <!-- Page Content -->
          <div id="page-content-wrapper" class="graybg">
              <section class="container-fluid ">

              <div class="forgot-pass">
                   	<h2> Forgot password? </h2>


  <div class="sub-heading"><p><strong>RETRIEVE YOUR PASSWORD HERE</strong> </p>

  <p>Please enter your email address below. You will receive a link to reset your password.</p>
  </div>


           			 <div class="forgot-form">
                   <form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="form-validate">

                  	 <div class="textbox-area">
                     <div class="input-box">
                          <input type="text"  placeholder="Email Address"  autocapitalize="off" autocorrect="off" spellcheck="false" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>" />
                      </div>
                      <div class="error"> <p class="required"><?php echo $this->__('* Required Fields') ?></p>
  </div>
                      </div>
                      <div class="actions">
                      <input  type="submit" class="default-btn submit-form" value="send me">
                      </div>
                      <?php echo $this->getChildHtml('form.additional.info'); ?>
                       <div class="clearfix"></div>
                     </form>

                  </div>



              </div>

              </section>
          </div>
          <!-- /#page-content-wrapper -->
    </div>
  </div>




</div>
                </div>
    </div>
  </div>

</div>
